---
- name: Gather IOS Version from Cisco Switch
  hosts: 10.230.163.6
  gather_facts: no

  vars: # for execution environment
  
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
    
  tasks:
    - name: Gather Cisco IOS facts
      cisco.ios.ios_facts:
      register: ios_info

    - name: Display IOS Version
      command: show version
      debug:
        msg: "The IOS Version is {{ ios_info.ansible_facts.net_version }}"
