---
- name: Gather IOS Version from Cisco Switch
  hosts: 10.230.163.6
  gather_facts: no
  tasks:
    - name: Gather Cisco IOS facts
      cisco.ios.ios_facts:
      register: ios_info

    - name: Display IOS Version
      debug:
        msg: "The IOS Version is {{ ios_info.ansible_facts.net_version }}"
