---
- name: "Ansible Network"
  hosts: 10.230.192.12
  gather_facts: no

  vars: # for execution environment
  
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: fabric 315 show inventory
      cisco.ios.ios_command:
        commands: fabric 315 show inventory
      register: output  # This stores the output in a variable named 'output'

    - name: Print output
      debug:
        msg: "{{ output.stdout_lines }}"  # This prints the output
