---
- name: "Ansible Network"
  hosts: 10.230.163.6,10.99.127.73
  gather_facts: no

  vars: # for execution environment
  
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: show version
      cisco.ios.ios_command:
        commands: show version
      register: output  # This stores the output in a variable named 'output'

    - name: Print output
      debug:
        msg: "{{ output.stdout_lines }}"  # This prints the output
